name: CastleSiege
version: '2.0.8'
main: me.cbhud.castlesiege.CastleSiege
author: cbhud
api-version: '1.20'
depend: [Regenerato]
softdepend:
  - PlaceholderAPI
  - FastAsyncWorldEdit
  - Multiverse-Core
commands:
  cse:
    description: Main command for Castle Siege plugin.
    usage: /cse <join|randomjoin|leave|stats|arena|coins|setlobby>
